### ISSUE TITLE
Missing 1.2.3?

### ISSUE THREAD

**Issue by au-phiware** [MatterHackers/MatterControlPlugins#2]
How come there's no branch to correspond to MatterControl's 1.2.3? (MatterControl@9e62c6b52399eddfc5fe0f5a877d930879e75f94)

Also, have you considered using tags to designate releases?

The reason I ask is because I'm writing an ebuild file for Gentoo's packaging system.

**Comment by jlewin** [comment]
The 1.2.3 branch doesn't exist because this repository is no longer used. Thanks for the catch and I've updated the wiki and will look into dropping the repo.

**Comment by au-phiware** [comment]
Ah, I see. I have completed the gentoo ebuild! In case you are interested, find it here: https://github.com/au-phiware/gentoo-overlay
